### ISSUE TITLE
[Suggestion] Terminal GUI Sorting Options

### ISSUE THREAD

**Issue by oitsjustjose** [unascribed/CorrelatedPotentialistics#3]
Thought it was basically the only thing that makes me still miss Applied Energistics for its basic purposes: alternative sorting methods for the Terminal's GUI. Not sure if you want to take a look at JEI's code to see how he does it, but the biggest ones to me that would be cool are:
1. Quantity (already currently used)
2. Alphabetical
3. ModID (this one is most used by me, honestly) - starting with Minecraft first (like JEI)

0.1.3 is great by the way!! Waiting for BC to update to resolve a recurring crash on my server, then I'm tossing it on there! :D

**Comment by unascribed** [comment]
Adding alternative sorting modes is actually really simple, it's just a new kind of Comparator. (The current sorting is actually done with [one line of code](https://github.com/unascribed/CorrelatedPotentialistics/blob/master/src/main/java/com/unascribed/correlatedpotentialistics/inventory/ContainerVT.java#L148).)

Though I'm not sure where to put the config for it; I never liked how AE hung them off the side of the GUI, and it really should be a per-user preference rather than per-terminal (or maybe both?)

Maybe I'll throw it next to the search bar.
